name: kmainfosec_sqli_demo
description: A demo of multi-threaded SQLi attacks in Dart developed in KMAINFOSEC course.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
